### ISSUE TITLE
Encoding of attachments

### ISSUE THREAD

**Issue by KamilaHasanbega** [e2email-org/e2email#11]
Right now I'm inserting the attachments as base64 string as per as I understand it, it would work with 7bit content transfer encoding, but I have a few issues I need to clarify.

1. Is 64bit encoding right in the case, and inputing files as strings or should I go with buffers/other?
2. Does this work for the android when sending emails (per as I'm aware, Boateng is not doing base64 and I believe we should coordinate so that the messages could be read in every device)?

@kbsriram Please let me know what do you think about this.

**Comment by koto** [comment]
Content-Tranfer-Encoding base64 for the attachments is a safe choice I think. We can revisit this later.

**Comment by koto** [comment]
This is safe to close.
